#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "quizzes"
name = "Quizzes"
description.en = "Multiple choice quiz platform with results analysis interface"
description.fr = "Plate-forme de quizzes à choix multiples (QCM) avec interface d'analyse des résultats"

version = "1.3.0~ynh3"

maintainers = []

[upstream]
license = "AGPL-3.0-only"
code = "https://github.com/hipay/quizzes/"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = "not_relevant"

sso = "not_relevant"

disk = "50M"
ram.build = "80M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "https://github.com/hipay/quizzes/archive/refs/tags/v1.3.0.tar.gz"
    sha256 = "885f91a81c3c1d5e652fd2a4e6d910680076e35258a3a13651bdf08700c85f3a"

    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "mutt",
        "php7.4-cli",
        "php7.4-mbstring",
    ]
