#!/bin/bash


source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace

#=================================================
# INSTALL WITH COMPOSER
#=================================================
ynh_script_progression "Installing $app with Composer..."

#REMOVEME? ynh_composer_install
ynh_composer_exec install --no-dev  --ignore-platform-reqs 2>&1

pushd "$install_dir"
    patch --strip=1 < "$YNH_APP_BASEDIR/sources/app-array_key_exists.patch"
popd

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

# Workaround because __DIR__ should not be replaced
dir="__DIR__"
ynh_config_add --template="qcm-dist.php" --destination="$install_dir/conf/qcm.php"

chmod 400 "$install_dir/conf/qcm.php"
chown "$app:$app" "$install_dir/conf/qcm.php"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_config_add_logrotate

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
